#### Exercise 6 - Test the "stratified_train_test_split" function with the iris dataset

In [2]:
from si.model_selection.split import train_test_split
from si.model_selection.split import stratified_train_test_split

from si.io.csv_file import read_csv

iris = read_csv('../datasets/iris/iris.csv', features=True, label=True)
iris.summary()

sepal_length  sepal_width  petal_length  petal_width
mean        5.843333     3.054000      3.758667     1.198667
median      5.800000     3.000000      4.350000     1.300000
min         4.300000     2.000000      1.000000     0.100000
max         7.900000     4.400000      6.900000     2.500000
var         0.681122     0.186751      3.092425     0.578532

In [9]:
import numpy as np

labels, counts = np.unique(iris.y, return_counts=True)
print(labels)
print(counts)
# count in percentage
print(counts / len(iris.y))


['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']
[50 50 50]
[0.33333333 0.33333333 0.33333333]


In [23]:
# stratified train test split
s_iris_train, s_iris_test = stratified_train_test_split(dataset=iris, test_size = 0.3, random_state=42)
s_labels, s_counts = np.unique(s_iris_train.y, return_counts=True)
st_labels, st_counts = np.unique(s_iris_test.y, return_counts=True)
# non stratified train test split
iris_train, iris_test = train_test_split(dataset=iris, test_size = 0.3, random_state=42)
labels, counts = np.unique(iris_train.y, return_counts=True)
tlabels, tcounts = np.unique(iris_test.y, return_counts=True)

print('Stratified train split:')
print(s_labels)
print(s_counts)
print(s_counts / len(s_iris_train.y), "\n")
print("non Stratifeid Train split:")
print(labels)
print(counts)
print(counts / len(iris_train.y), "\n", "\n")

print("Stratified Test split:")
print(st_labels)
print(st_counts)
print(st_counts / len(s_iris_test.y), "\n")
print('non stratified test split:')
print(tlabels)
print(tcounts)
print(tcounts / len(iris_test.y))



Stratified train split:
['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']
[35 35 35]
[0.33333333 0.33333333 0.33333333] 

non Stratifeid Train split:
['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']
[31 37 37]
[0.2952381  0.35238095 0.35238095] 
 

Stratified Test split:
['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']
[15 15 15]
[0.33333333 0.33333333 0.33333333] 

non stratified test split:
['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']
[19 13 13]
[0.42222222 0.28888889 0.28888889]


#### Exercise 7 - Test the "KNNRegressor" class using the "cpu.csv" dataset (regression).

In [3]:
cpu = read_csv('../datasets/cpu/cpu.csv', features=True, label=True)

In [13]:
from si.models.knn_regressor import KNNRegressor

data_train, data_test = train_test_split(dataset=cpu, test_size=0.30, random_state=42)

knn = KNNRegressor(k=3)

knn.fit(data_train)


score = knn.score(data_test)

print('The RMSE of the model is:', score)

The RMSE of the model is: 135.8292795753705


##### sklearn KNNRegressor

In [12]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error

data_train, data_test = train_test_split(dataset=cpu, test_size=0.30, random_state=42)

knn = KNeighborsRegressor(n_neighbors=3)

knn.fit(data_train.X, data_train.y)

score = mean_squared_error(data_test.y, knn.predict(data_test.X), squared=False)

print('The RMSE of the model is:', score)

The RMSE of the model is: 138.72569695775826
